version: '3.8'

services:
  nginx:
    build: ./nginx
    image: SEU_USUARIO_DOCKERHUB/nginx-devops:latest  # ← Adicione esta linha
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - app-network
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    restart: unless-stopped

  backend1:
    build: ./backend
    image: SEU_USUARIO_DOCKERHUB/backend-devops:latest  # ← Adicione esta linha
    environment:
      - SERVER_ID=Backend-1
      - PORT=3000
    networks:
      - app-network
    restart: unless-stopped

  backend2:
    build: ./backend
    image: SEU_USUARIO_DOCKERHUB/backend-devops:latest
    environment:
      - SERVER_ID=Backend-2
      - PORT=3000
    networks:
      - app-network
    restart: unless-stopped

  backend3:
    build: ./backend
    image: SEU_USUARIO_DOCKERHUB/backend-devops:latest
    environment:
      - SERVER_ID=Backend-3
      - PORT=3000
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge